name: nexgen_command
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  geolocator: 13.0.4
  network_info_plus: ^7.0.0
  image_picker: '>=1.1.2'
  url_launcher: ^6.0.0
  flutter_local_notifications: ^17.2.2
  google_maps_flutter: ^2.0.0
  flutter_blue_plus: ^2.0.0
  flutter_native_splash: ^2.0.0
  shared_preferences: ^2.0.0
  permission_handler: ^12.0.1
  speech_to_text: ^7.0.0
  http: ^1.0.0
  vector_math: ^2.0.0
  multicast_dns: 0.3.3
  flutter_riverpod: ^2.5.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  firebase_core: ^4.3.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  cloud_functions: ^6.0.5
  firebase_storage: ^13.0.5
  app_links: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/nexgen_logo.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#121212"
  color_dark: "#121212"
  image: assets/images/nexgen_logo.png
  image_dark: assets/images/nexgen_logo.png
  android_12:
    color: "#121212"
    color_dark: "#121212"
    image: assets/images/nexgen_logo.png
    image_dark: assets/images/nexgen_logo.png
  android: true
  ios: true
